- yum: name={{ item }} state=present
  with_items:
    - gcc
    - git
    - lua-devel
    - make
    - mercurial
    - ncurses-devel
    - perl-ExtUtils-Embed
    - perl-devel
    - python-devel
    - rpm-build

- git:
    repo: https://github.com/vim/vim.git
    dest: "{{ vim_srcdir }}/vim"

- command: "{{ item }}"
  args:
    chdir: "{{ vim_srcdir }}/vim"
    creates: "{{ vim_bindir }}/vim"
  with_items:
    - "./configure {{ vim_configure_options }}"
    - "make"
    - "make install"

- file:
    src: "{{ vim_bindir }}/vim"
    dest: "{{ vim_bindir }}/vi"
    state: link

