- yum: name={{ item }} state=present
  with_items:
    - gcc
    - make
    - mercurial
    - ncurses-devel
    - perl-ExtUtils-Embed
    - perl-devel
    - python-devel
    - rpm-build

- command: hg clone https://vim.googlecode.com/hg/ vim7.4
  args:
    chdir: /usr/local/src
    creates: /usr/local/src/vim7.4

- command: "{{ item }}"
  args:
    chdir: /usr/local/src/vim7.4
    creates: /usr/local/bin/vim
    removes: /usr/local/src/vim7.4
  with_items:
    - "./configure --with-local-dir=/usr --enable-multibyte --enable-tclinterp --disable-darwin --disable-xsmp --disable-netbeans --disable-gtktest --disable-gpm --disable-selinux --without-gnome"
    - "make"
    - "make install"

- file:
    src: /usr/local/bin/vim
    dest: /usr/local/bin/vi
    state: link

